name: Black code

on:
  push:
    branches:
      - master
      - V0.1
      - V0.1-curses

jobs:
  lint:
     name: black lint
     runs-on: ubuntu-latest
     
     steps:
       - name: Setup Python
         uses: actions/setup-python@v2
       - name: Setup Black
         run: python -m pip install black
       - name: Black Code
         run: python -m black burkejasonj/falloutText/src/com.JandL.falloutText
